language: python
cache: pip
dist: bionic

addons:
  apt:
    packages:
      - sqlite3
      - gdal-bin
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - spatialite-bin
      - libsqlite3-mod-spatialite

services:
  - docker
  - redis-server

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.2,<2.3"
  - DJANGO="django>=3.0,<3.1"

branches:
  only:
    - master

before_install:
  - pip install -U -r requirements-test.txt
  - npm install -g jshint

install:
  - pip install -U -e .
  - pip install $DJANGO
  - ./install-dev.sh

script:
  - ./run-qa-checks
  - coverage run --source=openwisp_controller runtests.py
  # SAMPLE tests do not influence coverage, so we can speed up tests with --parallel
  - SAMPLE_APP=1 ./runtests.py --parallel --keepdb

after_success:
  coveralls
