language: python
os: linux
cache: pip
dist: trusty

addons:
  apt:
    packages:
      - sqlite3
      - gdal-bin
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev

python:
  - "3.5"
  - "2.7"

env:
  - DJANGO="django>=1.11,<1.12"
  - DJANGO="django>=2.0,<2.1"

jobs:
  exclude:
   - python: "2.7"
     env: DJANGO="django>=2.0,<2.1"

branches:
  only:
    - master

before_install:
  - export PIPENV_IGNORE_VIRTUALENVS=1
  - pip install -U pipenv
  - pipenv install --dev --skip-lock
  - pipenv run lint
  - pipenv run isort

install:
  - export PIPENV_IGNORE_VIRTUALENVS=1
  - pipenv install --skip-lock $DJANGO
  # fix issues with travis
  - pipenv install --skip-lock "attrs>=17.4.0" six packaging
  # fix issue with spatialie on python 2
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then pipenv install --skip-lock git+git://github.com/tinio/pysqlite.git@extension-enabled#egg=pysqlite; fi
  - pipenv run install_dev
  - pipenv run pip freeze

script:
  - export PIPENV_IGNORE_VIRTUALENVS=1
  # for some reason the migrations check is failing only on django 2.0
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pipenv run ./tests/manage.py makemigrations config pki --dry-run | grep "No changes detected"; fi
  - pipenv run coverage run --source=openwisp_controller runtests.py
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      # gets commit message of last commit before pull request merge
      COMMIT_MESSAGE=$(git log $TRAVIS_PULL_REQUEST_SHA --format=%B -n 1)
      printf "Checking commit message:\n\n"
      printf "$COMMIT_MESSAGE\n\n"
      pipenv run checkcommit --message "$COMMIT_MESSAGE"
    fi

after_success:
  pipenv run coveralls
